# Generated by Django 4.2 on 2023-04-09 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tvTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(help_text='How Long is the Show')),
                ('show_name', models.CharField(help_text='Enter Show Name', max_length=20)),
                ('days_on', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thur', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=10)),
                ('active', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=5)),
                ('watcher', models.CharField(choices=[('jennifer', 'Jennifer'), ('erik', 'Erik')], max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('provider', models.CharField(choices=[('paramount', 'Paramount+'), ('hbo', 'HBO Max'), ('hulu', 'Hulu'), ('netflix', 'Netflix'), ('prime', 'Prime')], max_length=15)),
            ],
            options={
                'verbose_name': "Let's Watch TV",
                'verbose_name_plural': "Let's Watch TV",
            },
        ),
    ]
