# Generated by Django 4.2 on 2023-04-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvtime',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
